name: Development Workflow

on:
  push:
    branches: [main]#

# Here the environment variable is declared in workflow level
env:
  # Replace with your Orchestrator Values 
  ORCH_URL: "https://cloud.uipath.com"
  ORCH_TENANT: DefaultTenant
  ORCH_CLIENT_ID: 8a08525d-7e62-46b4-a3a9-6b90f7c573d5
  ORCH_USER_KEY: 3W^f~bam~V@Ou#!T7W44nXzj)7%pdN)%TnEH(z!Rc%vSHm_DKxUb1Q@Iz6D@qp4U
  ORCH_ACC_NAME: wondethfcjxw
  CLI_URL: "https://uipath.pkgs.visualstudio.com/Public.Feeds/_packaging/UiPath-Official/nuget/v3/flat2/UiPath.CLI.Windows/25.4.9364.27216/UiPath.CLI.Windows.25.4.9364.27216.nupkg"

jobs:
  print-details:
    runs-on: self-hosted
    #runs-on: self-hosted
    steps:
      - name: echo-default-env-variables
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
  #---------------------------------------------------------------------------------------        
# cleaner:
#    runs-on: windows-latest
#    #runs-on: self-hosted
#    steps:
#      - name: Runner workspace path
#        run: |
#          echo "Cleaning up previous run"
#          rm -rf "${{ github.workspace }}"
#--------------------------------------------------------------------------------------
  build-uipath-nuget-package:
    # You should be able to run on windows 2019 or windows latest
    #needs: cleaner
    runs-on: self-hosted
    #runs-on: self-hosted
    steps: 
      - name: Check out repository code
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4
      - name: Build Nuget Package
        shell: powershell
        run:  C:\\uipcli\\tools\\uipcli.exe package pack ${{ github.workspace }}\project.json -destination_folder ${{ github.workspace }}\package -autoVersion
      - name: Upload UiPath Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
           package/*.*
           scripts/*.ps1
  #--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  publish-uipath-nuget-package-Dev:
    needs: build-uipath-nuget-package
    runs-on: self-hosted
    #runs-on: self-hosted
    steps: 
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
      - name: Publish Nuget Package to DEV
        shell: powershell
        run: |
         ${{ github.workspace }}\scripts\UiPathDeploy.ps1 -packages_path ${{ github.workspace }}\package -orchestrator_url ${{env.ORCH_URL}} ${{env.ORCH_TENANT}} -a ${{env.ORCH_ACC_NAME}} -I ${{env.ORCH_CLIENT_ID}}  -s ${{env.ORCH_USER_KEY}}  --applicationscope "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines OR.Monitoring OR.Robots OR.Settings OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Users" -o "Shared" -cli_url "C:\uipcli\tools\uipcli.exe"



